### ISSUE TITLE
can't work

### ISSUE THREAD

**Issue by pcschoolleo** [plang/phonegap-l10n#1]
hi
i am a starter,this is my index.html in android
but it only show on the phone in en language
Yes
No
oui
non

what is wrong with me
my code should show 
Yes
Yes
Yes
No

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<link href="jquery-mobile/jquery.mobile.theme-1.0.min.css" rel="stylesheet" type="text/css" />
<link href="jquery-mobile/jquery.mobile.structure-1.0.min.css" rel="stylesheet" type="text/css" />

<script src="jquery-mobile/jquery-1.6.4.min.js" type="text/javascript"></script>

<script src="jquery-mobile/jquery.mobile-1.0.min.js" type="text/javascript"></script>

<script src="localization.js" type="text/javascript"></script>

```
<script type="text/javascript" charset="utf-8">

// Wait for device API libraries to load
//
function onLoad() {
    document.addEventListener("deviceready", onDeviceReady, false);
}

// device APIs are available
//
function onDeviceReady() {
   Localization.initialize
```

(
    // Dictionnary
    { 
        zh-rTW: {
            oui: "Oui",
            non: "Non"
        },

```
    en: {
        oui: "Yes",
        non: "No"
    }

},
// Fallback language
"en"
```

); // Now safe to use device APIs
    }

```
</script>
```

</head>

<body>
<span class="l10n-oui">Yes</span>
<span class="l10n-oui">No</span>
<span class="l10n-oui">oui</span>
<span class="l10n-non">non</span>
</body>
</html>

**Comment by plang** [comment]
Hi, I cannot see much with the badly formatted piece of code you sent. But I could read you have defined a language called "zh-rTW". I don't think this language exists anywhere on the world, so the fallback language will be always used. It is english in your case.

**Comment by plang** [comment]
I think you are simply using the library the wrong way, so I close this issue.
